org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=1.20.1
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
mod_id=changede
mod_name=Changed:Extra
mod_license=MIT License
mod_version=1.1.3
mod_group_id=github.com.gengyoubo
mod_authors=gengyoubo
displayURL=https://github.com/gengyoubo/changed-extra
mod_description="Technology is our mission: to develop better forms and understand latex creatures themselves."
rootProject.name = 'changede'
